name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install -r bin/requirements.txt
    - run: pip install pylint
    - run: pylint bin/backcheck_publishedurl.py
    - run: pylint bin/check_published_image.py
    #- run: pylint bin/process_check.py
    - run: pylint bin/update_dynamodb_published_skeletons.py
    - run: pylint bin/update_dynamodb_published_stacks.py
    - run: pylint bin/update_dynamodb_publishing_doi.py
